/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gameengine_6 (
    input clk,
    input rst,
    input time_out,
    input [15:0] aluout,
    input game_start,
    input game_end,
    output reg [16:0] opcode
  );
  
  
  
  localparam OPC_CMP_TIME_FRAME = 17'h1a800;
  
  localparam OPC_CMP_FOOD = 17'h19a80;
  
  localparam OPC_INCREMENT_SCORE = 17'h00508;
  
  localparam OPC_MOVE_SNK_HD = 17'h00040;
  
  localparam OPC_UPDATE_SNK_POS = 17'h00020;
  
  localparam OPC_SPAWN_FOOD = 17'h00010;
  
  localparam OPC_RENDER = 17'h00006;
  
  localparam OPC_RESET = 17'h00001;
  
  localparam WAIT_FRAME_gamefsm = 4'd0;
  localparam CHECK_TIME_gamefsm = 4'd1;
  localparam GAME_OVER_gamefsm = 4'd2;
  localparam GAME_START_gamefsm = 4'd3;
  localparam CHECK_EAT_gamefsm = 4'd4;
  localparam INCREMENT_SCORE_gamefsm = 4'd5;
  localparam SPAWN_FOOD_gamefsm = 4'd6;
  localparam MOVE_SNK_HD_gamefsm = 4'd7;
  localparam UPDATE_SNAKE_POS_gamefsm = 4'd8;
  localparam CHECK_WRAP_gamefsm = 4'd9;
  localparam RENDER_gamefsm = 4'd10;
  
  reg [3:0] M_gamefsm_d, M_gamefsm_q = WAIT_FRAME_gamefsm;
  
  always @* begin
    M_gamefsm_d = M_gamefsm_q;
    
    opcode = 1'h0;
    
    case (M_gamefsm_q)
      WAIT_FRAME_gamefsm: begin
        opcode = 17'h1a800;
        if (aluout == 1'h1) begin
          M_gamefsm_d = CHECK_TIME_gamefsm;
        end
      end
      CHECK_TIME_gamefsm: begin
        if (time_out == 1'h1) begin
          M_gamefsm_d = GAME_OVER_gamefsm;
        end else begin
          M_gamefsm_d = CHECK_EAT_gamefsm;
        end
      end
      CHECK_EAT_gamefsm: begin
        opcode = 17'h19a80;
        if (aluout == 1'h1) begin
          M_gamefsm_d = INCREMENT_SCORE_gamefsm;
        end else begin
          M_gamefsm_d = MOVE_SNK_HD_gamefsm;
        end
      end
      INCREMENT_SCORE_gamefsm: begin
        opcode = 17'h00508;
        M_gamefsm_d = SPAWN_FOOD_gamefsm;
      end
      SPAWN_FOOD_gamefsm: begin
        opcode = 17'h00010;
        M_gamefsm_d = MOVE_SNK_HD_gamefsm;
      end
      MOVE_SNK_HD_gamefsm: begin
        opcode = 17'h00040;
        M_gamefsm_d = UPDATE_SNAKE_POS_gamefsm;
      end
      UPDATE_SNAKE_POS_gamefsm: begin
        opcode = 17'h00020;
        M_gamefsm_d = RENDER_gamefsm;
      end
      RENDER_gamefsm: begin
        opcode = 17'h00006;
        M_gamefsm_d = WAIT_FRAME_gamefsm;
      end
      GAME_OVER_gamefsm: begin
        if (game_start) begin
          M_gamefsm_d = GAME_START_gamefsm;
        end else begin
          M_gamefsm_d = GAME_OVER_gamefsm;
        end
      end
      GAME_START_gamefsm: begin
        opcode = 17'h00001;
        M_gamefsm_d = CHECK_TIME_gamefsm;
      end
    endcase
    if (game_end) begin
      M_gamefsm_d = GAME_OVER_gamefsm;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_gamefsm_q <= 1'h0;
    end else begin
      M_gamefsm_q <= M_gamefsm_d;
    end
  end
  
endmodule
