/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module score_9 (
    input clk,
    input rst,
    input wescr,
    input [15:0] aluout,
    output reg out
  );
  
  
  
  always @* begin
    out = 1'h0;
  end
endmodule
