/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module food_11 (
    input clk,
    input rst,
    input wefood,
    output reg [11:0] food_pos
  );
  
  
  
  reg [3:0] M_pos_x_d, M_pos_x_q = 1'h0;
  reg [3:0] M_pos_y_d, M_pos_y_q = 1'h0;
  reg [3:0] M_pos_z_d, M_pos_z_q = 1'h0;
  
  always @* begin
    if (wefood) begin
      
    end
    food_pos = {M_pos_x_q, M_pos_y_q, M_pos_z_q};
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pos_x_q <= 1'h0;
      M_pos_y_q <= 1'h0;
      M_pos_z_q <= 1'h0;
    end else begin
      M_pos_x_q <= M_pos_x_d;
      M_pos_y_q <= M_pos_y_d;
      M_pos_z_q <= M_pos_z_d;
    end
  end
  
endmodule
