/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module render_12 (
    input clk,
    input rst,
    input [11:0] snk_hd_pos,
    input [11:0] snk_bd_pos,
    input [11:0] snk_tl_pos,
    input [11:0] food_pos,
    input wernd,
    output reg [4:0] cols,
    output reg [24:0] rows
  );
  
  
  
  reg [124:0] M_food_state_d, M_food_state_q = 1'h0;
  reg [124:0] M_snake_state_d, M_snake_state_q = 1'h0;
  reg [124:0] M_led_state_d, M_led_state_q = 1'h0;
  
  always @* begin
    M_led_state_d = M_led_state_q;
    
    M_led_state_d = 1'h0;
    cols = 1'h0;
    rows = 1'h0;
    if (wernd) begin
      
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_food_state_q <= 1'h0;
      M_snake_state_q <= 1'h0;
      M_led_state_q <= 1'h0;
    end else begin
      M_food_state_q <= M_food_state_d;
      M_snake_state_q <= M_snake_state_d;
      M_led_state_q <= M_led_state_d;
    end
  end
  
endmodule
