/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sevenseg_4 (
    input [15:0] d,
    output reg [13:0] q
  );
  
  
  
  reg [3:0] tens;
  
  reg [3:0] ones;
  
  reg [3:0] tens_mod;
  
  reg [3:0] ones_mod;
  
  reg [6:0] tens_out;
  
  reg [6:0] ones_out;
  
  always @* begin
    ones = d[0+3-:4];
    if (ones > 4'ha) begin
      ones_mod = ones - 4'ha;
    end else begin
      ones_mod = ones;
    end
    tens = (d / 4'ha);
    if (tens > 4'ha) begin
      tens_mod = tens - 4'ha;
    end else begin
      tens_mod = tens;
    end
    
    case (ones)
      1'h1: begin
        ones_out = 7'h30;
      end
      2'h2: begin
        ones_out = 7'h6d;
      end
      2'h3: begin
        ones_out = 7'h79;
      end
      3'h4: begin
        ones_out = 7'h33;
      end
      3'h5: begin
        ones_out = 7'h5b;
      end
      3'h6: begin
        ones_out = 7'h5f;
      end
      3'h7: begin
        ones_out = 7'h70;
      end
      4'h8: begin
        ones_out = 7'h7f;
      end
      4'h9: begin
        ones_out = 7'h73;
      end
      default: begin
        ones_out = 7'h7e;
      end
    endcase
    
    case (tens)
      1'h1: begin
        tens_out = 7'h30;
      end
      2'h2: begin
        tens_out = 7'h6d;
      end
      2'h3: begin
        tens_out = 7'h79;
      end
      3'h4: begin
        tens_out = 7'h33;
      end
      3'h5: begin
        tens_out = 7'h5b;
      end
      3'h6: begin
        tens_out = 7'h5f;
      end
      3'h7: begin
        tens_out = 7'h70;
      end
      4'h8: begin
        tens_out = 7'h7f;
      end
      4'h9: begin
        tens_out = 7'h73;
      end
      default: begin
        tens_out = 7'h7e;
      end
    endcase
    q = {tens_out, ones_out};
  end
endmodule
