/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module timer_10 (
    input clk,
    input rst,
    input wetmr,
    output reg [5:0] game_time,
    output reg time_out,
    output reg [15:0] clk_count,
    output reg [15:0] frame_period
  );
  
  
  
  localparam FRAME_PERIOD = 16'h1fc0;
  
  localparam FIFTY_MILION = 26'h2faf080;
  
  reg [26:0] M_clk_counter_d, M_clk_counter_q = 1'h0;
  reg [5:0] M_game_time_counter_d, M_game_time_counter_q = 1'h0;
  reg [26:0] M_game_clk_counter_d, M_game_clk_counter_q = 1'h0;
  
  always @* begin
    M_clk_counter_d = M_clk_counter_q;
    M_game_time_counter_d = M_game_time_counter_q;
    M_game_clk_counter_d = M_game_clk_counter_q;
    
    frame_period = 16'h1fc0;
    M_clk_counter_d = M_clk_counter_q + 1'h1;
    M_game_clk_counter_d = M_game_clk_counter_q + 1'h1;
    clk_count = M_clk_counter_q[11+15-:16];
    if (wetmr) begin
      M_clk_counter_d = 1'h0;
    end
    if (M_game_clk_counter_q > 26'h2faf080) begin
      M_game_time_counter_d = M_game_time_counter_q + 1'h1;
      M_game_clk_counter_d = 1'h0;
    end
    game_time = 6'h3c - M_game_time_counter_q;
    if (M_game_time_counter_q > 6'h3c) begin
      time_out = 1'h1;
    end else begin
      time_out = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_clk_counter_q <= 1'h0;
      M_game_time_counter_q <= 1'h0;
      M_game_clk_counter_q <= 1'h0;
    end else begin
      M_clk_counter_q <= M_clk_counter_d;
      M_game_time_counter_q <= M_game_time_counter_d;
      M_game_clk_counter_q <= M_game_clk_counter_d;
    end
  end
  
endmodule
